apiVersion: v1
kind: Secret
metadata:
  name: repo-github
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/dipakrasal2009/one2n-SRE-Bootcamp.git
  username: dipakrasal2009
  password: <pat>

