apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-db
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dipakrasal2009/one2n-SRE-Bootcamp.git
    targetRevision: main
    path: helm/student-db
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: student-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

